apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: dummy-ingress
 namespace: fs
 annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: dummy.fullstack.com
   http:
    paths:
    - path: /
      pathType: Prefix
      backend:
       service:
        name: dummy-server
        port:
         number: 8080